In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'1.0.3'

In [3]:
pd.options.display.float_format = '{:.2f}'.format

In [4]:
np.set_printoptions(precision=1)

In [5]:
x1 = np.random.rand(2,5)*10
x1

array([[1. , 6.4, 3.5, 3.7, 1.6],
       [0.8, 3.6, 0.8, 0.6, 9.5]])

In [6]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0. , -0.5, -0.6, -0.6, -1. ],
       [-0.7, -0.8, -0.2, -0.5, -1. ]])

In [7]:
np.concatenate([x1,x2],axis=1)

array([[ 1. ,  6.4,  3.5,  3.7,  1.6, -0. , -0.5, -0.6, -0.6, -1. ],
       [ 0.8,  3.6,  0.8,  0.6,  9.5, -0.7, -0.8, -0.2, -0.5, -1. ]])

In [8]:
s1 = pd.Series(x1[0], index=['a','b','c','d','e'])
s1

a   0.97
b   6.37
c   3.46
d   3.70
e   1.65
dtype: float64

In [9]:
s2 = pd.Series(x1[0], index=['c','d','e','f','g'])
s2

c   0.97
d   6.37
e   3.46
f   3.70
g   1.65
dtype: float64

In [10]:
pd.concat([s1,s2], axis=1)

0    1
a 0.97  nan
b 6.37  nan
c 3.46 0.97
d 3.70 6.37
e 1.65 3.46
f  nan 3.70
g  nan 1.65

In [11]:
s1.reset_index()

index    0
0     a 0.97
1     b 6.37
2     c 3.46
3     d 3.70
4     e 1.65

In [12]:
s1.reset_index(drop=True)

0   0.97
1   6.37
2   3.46
3   3.70
4   1.65
dtype: float64

In [13]:
s3 = s1.reset_index(drop=True)
s3
s4 = s2.reset_index(drop=True)
s4

s5 = pd.concat([s3,s4], axis=1)
s5

0    1
0 0.97 0.97
1 6.37 6.37
2 3.46 3.46
3 3.70 3.70
4 1.65 1.65

In [14]:
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=['a','b'])
df1

a    b
0 2.11 5.51
1 7.16 1.49
2 5.93 2.34

In [15]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns=['a','b'],index=[2,3,4])
df2

a     b
2 -0.71 -0.53
3 -0.21 -0.39
4 -0.80 -0.15

In [16]:
pd.concat([df1,df2])

a     b
0  2.11  5.51
1  7.16  1.49
2  5.93  2.34
2 -0.71 -0.53
3 -0.21 -0.39
4 -0.80 -0.15

In [17]:
pd.concat([
    df1.reset_index(drop=True),
    df2.reset_index(drop=True)
    ],axis=1)

a    b     a     b
0 2.11 5.51 -0.71 -0.53
1 7.16 1.49 -0.21 -0.39
2 5.93 2.34 -0.80 -0.15

In [18]:
df1.append(df2)

a     b
0  2.11  5.51
1  7.16  1.49
2  5.93  2.34
2 -0.71 -0.53
3 -0.21 -0.39
4 -0.80 -0.15

In [19]:
df1.T.append(df2.T)

0    1     2     3     4
a 2.11 7.16  5.93   nan   nan
b 5.51 1.49  2.34   nan   nan
a  nan  nan -0.71 -0.21 -0.80
b  nan  nan -0.53 -0.39 -0.15

In [21]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [22]:
df.append(df1)

a    b
0 2.11 5.51
1 7.16 1.49
2 5.93 2.34

In [24]:
df = df.append(df1)

In [25]:
df

a    b
0 2.11 5.51
1 7.16 1.49
2 5.93 2.34